[package]
name = "hash"
version = "0.1.0"
authors = ["Jakub Chodubski <jchodubski@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
md-5 = "*"
